{"body":"&gt; Python's exceptions always unwind the stack, so all the evidence you have left is what printed on the error report. You lose all the context provided by the local state that was bound at the time.\r\n\r\nNo, Python tracebacks retain full stack frames.\r\n\r\nThe default `sys.excepthook` isn't very fancy, but you can set it to something like [this](http://ipython.scipy.org/screenshots/snapshot1.png) instead, or make it call `pdb.post_mortem` to let you inspect the context \"live\".  (You can do the same on application-caught exceptions too, of course)","controversiality":0,"stickied":false,"link_id":"t3_vr55","subreddit_id":"t5_2fwo","subreddit":"programming","created_utc":1166814167,"author_flair_css_class":null,"score":12,"ups":12,"author_flair_text":null,"author":"pjdelport","edited":false,"id":"cvrvx","parent_id":"t1_cvrho","gilded":0,"retrieved_on":1473809213,"distinguished":null,"timestamp_epoch":1566236775,"message_id":"45923-f404c8c8-8201-4123-aa0a-857348f0a61a-1566236775"}