{"retrieved_on":1473809764,"distinguished":null,"gilded":0,"parent_id":"t1_cwkxv","edited":false,"id":"cwl1m","author":"nostrademons","author_flair_text":null,"created_utc":1167607694,"author_flair_css_class":null,"ups":1,"score":1,"subreddit":"programming","stickied":false,"link_id":"t3_wixp","subreddit_id":"t5_2fwo","controversiality":0,"body":"Using Java 1.4 chained exceptions, or some homegrown wrapper exception?  Since Java 1.4, you can get at the original exception with getCause(), and it normally tries to include that in the stack trace (though it'll trim them if the chain gets too long).","timestamp_epoch":1566236781,"message_id":"60978-94f4e612-0017-425c-9d32-41f7b6d771ed-1566236781"}