{"body":"So... Every time I call a function that indicates failure in such a way, before I use the result, I have to check if the result really is the result or an error?\r\n\r\nThis is as bad as return-error-code. (Or am I missing something, as I know nothing about Caml ;-) ).","controversiality":0,"link_id":"t3_u1h2","stickied":false,"subreddit_id":"t5_2fwo","subreddit":"programming","author_flair_css_class":null,"created_utc":1165572899,"score":5,"ups":5,"author":"Gotebe","author_flair_text":null,"edited":false,"id":"cu3g1","parent_id":"t1_cu2hy","gilded":0,"retrieved_on":1473808067,"distinguished":null,"timestamp_epoch":1566236763,"message_id":"15707-b562963b-6d1c-4209-b855-17853141801a-1566236763"}