{"gilded":0,"distinguished":null,"retrieved_on":1473808651,"author_flair_text":null,"author":"shit","parent_id":"t1_cuws2","edited":false,"id":"cuyhs","subreddit":"programming","score":2,"ups":2,"author_flair_css_class":null,"created_utc":1166214987,"controversiality":0,"body":"It's intended for comparison with the Python example. It should be wrapped in a class + static main method that \"throws Exception\". The Python version also doesn't catch the exception (and that's good because in case of failure you get an error message + backtrace, simply catching an exception and doing nothing is the worst thing you can do).","subreddit_id":"t5_2fwo","link_id":"t3_utqb","stickied":false,"timestamp_epoch":1566236769,"message_id":"31337-ab2b9d6b-6cf4-44ad-9e79-cdf507eb34d3-1566236769"}